### ISSUE TITLE
pLink 2.3.2 cannot launch after system update

### ISSUE THREAD

**Issue by armadillocommander** [pFindStudio/pLink2#28] opened 2018-05-15 00:57 UTC
Hi, today after I installed the Windows 10 system update (Version 1803 OS build 17134.48), the pLink 2.3.2 cannot launch. The main window showed up in whole white and then the software crashed without any error or warning. Is there any way to fix? Thanks!

**Comment by 01joy** [comment] 2018-05-17 13:02
Hi @armadillocommander ,

Since we have no this version of Windows 10, so we can't reproduce your problem.

Please uninstall and reinstall pLink2 and try again.

**Comment by wgl91** [comment] 2018-05-21 19:48
Hello,
I have had a similar experience. pLink opens as a white screen and then almost immediately closes. I reinstalled pLink 2.3.2, but it still will not launch properly.

**Comment by 01joy** [comment] 2018-05-23 01:09
Hi @wgl91 ,

Is your OS the same as  (Version 1803 OS build 17134.48)?

How about uninstall the old pLink2, reboot the PC, and reinstall pLink2?

**Comment by 01joy** [comment] 2018-05-24 03:45
Hi @armadillocommander and @wgl91 ,

I have confirmed and reproduced the problem, it only happened on the latest Windows 10 system Version 1803. I have fixed this bug, and the new version of pLink2 will be released at the end of this week.

Thanks for reporting this bug.

**Comment by armadillocommander** [comment] 2018-05-24 23:20
Thank you so much!

**Comment by 01joy** [comment] 2018-05-30 06:37
Hi @armadillocommander and @wgl91 ，

This bug had been fixed in version pLink2.3.3, which is released today. Please download it from our website: http://pfind.ict.ac.cn/software/pLink/index.html#Downloads.

License since version 2.3.0 is still valid for this version.

**Closed** 2018-06-04 10:30 UTC
Labels: bug, help wanted
