### ISSUE TITLE
FDR Curve is not generated in pLink 2.3.2

### ISSUE THREAD

**Issue by armadillocommander** [pFindStudio/pLink2#27] opened 2018-05-02 16:44 UTC
In the HTML result report, the FDR curve graph is blank in pLink 2.3.2.

![fdr](https://user-images.githubusercontent.com/35280275/39537075-525dfd3c-4ded-11e8-8774-6425b84c5111.png)

**Comment by armadillocommander** [comment] 2018-05-03 15:18
I don't think that's the case. For my search, there were 40 cross-linked peptides and more than 1000 regular peptides identified under 5% FDR control, that should be enough for FDR evaluation.

![capture](https://user-images.githubusercontent.com/35280275/39585803-744d97b4-4eaa-11e8-8f79-1183b0b749e5.PNG)
![fdr](https://user-images.githubusercontent.com/35280275/39585821-8029f2da-4eaa-11e8-8363-ef8438cd86da.png)

**Comment by 01joy** [comment] 2018-05-04 01:56
Hi @armadillocommander ,
Please show me the all top1 results in reports folder, that's the first file with the shortest file name in reports folder. I mean something like the first file in Page 23 of [the user guide](http://pfind.ict.ac.cn/software/pLink/pLink2%20User%20Guide.pdf).

pLink2 will generate the FDR curve according to this file.

BTW, what's the format of your spectra file, RAW or MGF? If MGF, how did you extract it from RAW?

**Comment by armadillocommander** [comment] 2018-05-15 00:45
Hi, here are the filtered and unfiltered .csv files in reports directory. I used .raw file directly.

Unfiltered: [Potato_PGSC_2018.05.02.zip](https://github.com/pFindStudio/pLink2/files/2003062/Potato_PGSC_2018.05.02.zip)

Filtered: [filtered.zip](https://github.com/pFindStudio/pLink2/files/2003064/filtered.zip)

**Comment by 01joy** [comment] 2018-05-17 13:30
Hi @armadillocommander ,

I have reproduced your problem, because we have changed the format of CSV file in reports, but the draw program hasn't been changed accordingly. So, it can't generate the fdr curve.

We have fixed this bug and will release a new version at the end of this month.

Thanks for your bug report.

**Comment by 01joy** [comment] 2018-05-30 06:37
Hi @armadillocommander ，

This bug had been fixed in version pLink2.3.3, which is released today. Please download it from our website: http://pfind.ict.ac.cn/software/pLink/index.html#Downloads.

License since version 2.3.0 is still valid for this version.

**Closed** 2018-06-04 10:30 UTC
Labels: bug
