### ISSUE TITLE
can't load a protein database

### ISSUE THREAD

**Issue by gPirkes** [pFindStudio/pLink2#15] opened 2018-01-19 10:10 UTC
Hi, 
I've been trying to get pLink2 to work. However, I seem to be unable to load a Protein Database. Every time I press the Customize Database drop-down menu entry, I can see the pConfic process pop up in the Task Manger. Just very shortly after that I can see a Windows Problem Reporting Task pop up, then pConfig and the Windows Error Reporting Tasks are closed without any error message. I think it might be a permission problem, since I have to run it as administrator or it wont start. It doesn't have anything to do with the folder permissions, and I dont understand why it has to run as administrator, since my user account has the same rights to run the executables as the administrator!
Cheers, 
Georg

**Comment by 01joy** [comment] 2018-01-20 03:38
Hi @gPirkes ,

I'm sorry that pLink2 didn't work with you.

pLink2 will be installed in C:\Program Files\pLink2 directory by default, which need administrator rights to write. We will change the default installation folder in the next version, so that it won't ask for administrator rights again.

As for pConfig, it is used to configure all the meta data in pLink2, those are *.ini files in pLink2/bin folder. Have you ever configure any meta data, for example xlink.ini?  Could you provide me with all the *.ini files in pLink2/bin folder, so that I can reproduce your problem?

**Comment by gPirkes** [comment] 2018-01-26 11:23
I did insall it in my User subdirectory, to get around the administrator rights problem, but that did not change anything - in fact, i am still promted for administrator credentials when i try to start the program. 
I wasn't able to configure anyhting, since pConfig crashes every time i try to change settings. 
I have attached my ini files. 

[ini_files.zip](https://github.com/pFindStudio/pLink2/files/1667545/ini_files.zip)

**Comment by 01joy** [comment] 2018-01-26 12:58
Hi @gPirkes ,

I have checked all your ini files, everything is ok. Can you run pConfig with administrator credentials alone? If not, could you try to install it in non-user directory, such as D:\ disk?

We will improve the user experience by not ask administrator credentials every time in the next version.

**Comment by 01joy** [comment] 2018-01-31 15:39
Hi @gPirkes  ,

This bug has been solved in pLink 2.3.0, which is released on January 31, 2018, please goto http://pfind.ict.ac.cn/software/pLink/index.html#Downloads to download the new version and try again.

Thanks for your feedback.

**Closed** 2018-02-02 03:48 UTC
Labels: bug

**Comment by gPirkes** [comment] 2018-02-02 08:30
Thank you for your quick responses - Do i need a new licence for pLink 2.3?

Cheers, 
Georg

**Comment by 01joy** [comment] 2018-02-05 01:23
Yes, software activation methods have been changed because of the bug on some Windows 10 Pro, you should re-apply the license file to activate pLink 2, we apologize for that.
