### ISSUE TITLE
Spectra loading stopped

### ISSUE THREAD

**Issue by armadillocommander** [pFindStudio/pLink2#12] opened 2018-01-10 01:11 UTC
Hi,

I tried to run a disulfide bond searching in pLink 2. Once the search start, it stopped at spectra loading step (show as the message below). Anyone has idea? Thanks!

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract F:\Yiming\Sample1_rep3.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 28.875s. == == ==
[pParse] MS1list completes. 
[pParse] Processing Sample1_rep3.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 3853 
[pParse] Loading MS2 Spectra Number: 17319 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 40394 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 46 seconds. == == == =  
[pLink] Welcome to use pLink v2.2.1649, it will be expired on 20190101
[pLink] Search Engine initializing...
[pLink] Generating reverse database...
[pLink] Search identifier: LHZZZ
[pLink] Search Engine is ready to search.

[pLink] Start searching F:\Sample1_rep3_HCDFT.pf2, Labeling None
[pLink] Total spectra: 40394
[pLink] Loaded 5000 spectra, 5000 / 40394
[pLink] Loaded 5000 spectra, 10000 / 40394
[pLink] Loaded 5000 spectra, 15000 / 40394
[pLink] Loaded 5000 spectra, 20000 / 40394

**Comment by armadillocommander** [comment] 2018-01-11 21:50
I also checked the output in log.out. It stopped after "Peptide Bit Index Initialized".

[pLink] Total spectra: 40394
[pLink] Loaded 5000 spectra, 5000 / 40394
[debug] Spectra preprocessing...
[debug] Creating peptide index...
[pLink] Loaded 5000 spectra, 10000 / 40394
[debug] Spectra preprocessing...
[debug] Creating peptide index...
[pLink] Loaded 5000 spectra, 15000 / 40394
[debug] Spectra preprocessing...
[debug] Creating peptide index...
[debug] Peptide Bit Index Initialized.

**Comment by 01joy** [comment] 2018-01-12 01:56
Hi armadillocommander,

Did you use SS linker with Nonspecific enzyme?

It requests much more memory when digested with Nonspecific enzyme, I will try to fix this in the next version.

**Comment by vladtheimpalerSr** [comment] 2018-01-16 20:35
I have the same issue, using mgf and fasta files that pLink handled just fine. Enzyme used in search is trypsin. X-linker BS3, Stops loading spectra after 1st 5000. Windows 7 Pro 64 bit, i7-3820, 16 GB RAM. Memory used 47%.

**Comment by armadillocommander** [comment] 2018-01-16 22:15
@01joy @vladtheimpalerSr 

It's a trypsin digested protein sample. I wrote a script to reformat the fasta file I used for search, it now works fine. My guess the issue is related to the format of the fasta file, but I cannot confirm because there's no related information output in the log.

**Comment by 01joy** [comment] 2018-01-17 06:13
@vladtheimpalerSr @armadillocommander 

Could you provide me with the original fasta files so that I can reproduce the bug and try to fix it.

Thanks.

**Comment by vladtheimpalerSr** [comment] 2018-01-17 12:20
Attached


Vladimir Svetlov, PhD
Senior Research Scientist
Nudler Lab
Biochemistry & Molecular Pharmacology
NYU Medical Center
HHMI
________________________________

**Comment by vladtheimpalerSr** [comment] 2018-01-17 12:24
Can you send me your fasta file for comparison? Pretty please.


Vladimir Svetlov, PhD
Senior Research Scientist
Nudler Lab
Biochemistry & Molecular Pharmacology
NYU Medical Center
HHMI
________________________________

**Comment by vladtheimpalerSr** [comment] 2018-01-17 12:29
this dumbass thing don't support .fasta attachments


RpoC
MKDLLKFLKAQTKTEEFDAIKIALASPDMIRSWSFGEVKKPETINYRTFK
PERDGLFCARIFGPVKDYECLCGKYKRLKHRGVICEKCGVEVTQTKVRRE
RMGHIELASPTAHIWFLKSLPSRIGLLLDMPLRDIERVLYFESYVVIEGG
MTNLERQQILTEEQYLDALEEFGDEFDAKMGAEAIQALLKSMDLEQECEQ
LREELNETNSETKRKKLTKRIKLLEAFVQSGNKPEWMILTVLPVLPPDLR
PLVPLDGGRFATSDLNDLYRRVINRNNRLKRLLDLAAPDIIVRNEKRMLQ
EAVDALLDNGRRGRAITGSNKRPLKSLADMIKGKQGRFRQNLLGKRVDYS
GRSVITVGPYLRLHQCGLPKKMALELFKPFIYGKLELRGLATTIKAAKKM
VEREEAVVWDILDEVIREHPVLLNRAPTLHRLGIQAFEPVLIEGKAIQLH
PLVCAAYNADFDGDQMAVHVPLTLEAQLEARALMMSTNNILSPANGEPII
VPSQDVVLGLYYMTRDCVNAKGEGMVLTGPKEAERLYRSGLASLHARVKV
RITEYEKDANGELVAKTSLKDTTVGRAILWMIVPKGLPYSIVNQALGKKA
ISKMLNTCYRILGLKPTVIFADQIMYTGFAYAARSGASVGIDDMVIPEKK
HEIISEAEAEVAEIQEQFQSGLVTAGERYNKVIDIWAAANDRVSKAMMDN
LQTETVINRDGQEEKQVSFNSIYMMADSGARGSAAQIRQLAGMRGLMAKP
DGSIIETPITANFREGLNVLQYFISTHGARKGLADTALKTANSGYLTRRL
VDVAQDLVVTEDDCGTHEGIMMTPVIEGGDVKEPLRDRVLGRVTAEDVLK
PGTADILVPRNTLLHEQWCDLLEENSVDAVKVRSVVSCDTDFGVCAHCYG
RDLARGHIINKGEAIGVIAAQSIGEPGTQLTMRTFHIGGAASRAAAESSI
QVKNKGSIKLSNVKSVVNSSGKLVITSRNTELKLIDEFGRTKESYKVPYG
AVLAKGDGEQVAGGETVANWDPHTMPVITEVSGFVRFTDMIDGQTITRQT
DELTGLSSLVVLDSAERTAGGKDLRPALKIVDAQGNDVLIPGTDMPAQYF
LPGKAIVQLEDGVQISSGDTLARIPQESGGTKDITGGLPRVADLFEARRP
KEPAILAEISGIVSFGKETKGKRRLVITPVDGSDPYEEMIPKWRQLNVFE
GERVERGDVISDGPEAPHDILRLRGVHAVTRYIVNEVQDVYRLQGVKIND
KHIEVIVRQMLRKATIVNAGSSDFLEGEQVEYSRVKIANRELEANGKVGA
TYSRDLLGITKASLATESFISAASFQETTRVLTEAAVAGKRDELRGLKEN
VIVGRLIPAGTGYAYHQDRMRRRAAGEAPAAPQVTAEDASASLAELLNAG
LGGSDNE
>RpoA
MQGSVTEFLKPRLVDIEQVSSTHAKVTLEPLERGFGHTLGNALRRILLSS
MPGCAVTEVEIDGVLHEYST KEGVQEDILEILLNLKGLAVRVQGKDEVI
LTLNKSGIGPVTAADITHDGDVEIVKPQHVICHLTDENASI SMRIKVQR
GRGYVPASTRIHSEEDERPIGRLLVDACYSPVERIAYNVEAARVEQRTDL
DKLVIEMETNGT IDPEEAIRRAATILAEQLEAFVDLRDVRQPEVKEEKP
EFDPILLRPVDDLELTVRSANCLKAEAIHYIGD LVQRTEVELLKTPNLG
KKSLTEIKDVLASRGLSLGMRLENWPPASIADE
>RpoB
MVYSYTEKKRIRKDFGKRPQVLDVPYLLSIQLDSFQKFIEQDPEGQYGLEAAFRSVFPIQSYSGNSELQY
VSYRLGEPVFDVQECQIRGVTYSAPLRVKLRLVIYEREAPEGTVKDIKEQEVYMGEIPLMTDNGTFVING
TERVIVSQLHRSPGVFFDSDKGKTHSSGKVLYNARIIPYRGSWLDFEFDPKDNLFVRIDRRRKLPATIIL
RALNYTTEQILDLFFEKVIFEIRDNKLQMELVPERLRGETASFDIEANGKVYVEKGRRITARHIRQLEKD
DVKLIEVPVEYIAGKVVAKDYIDESTGELICAANMELSLDLLAKLSQSGHKRIETLFTNDLDHGPYISET
LRVDPTNDRLSALVEIYRMMRPGEPPTREAAESLFENLFFSEDRYDLSAVGRMKFNRSLLREEIEGSGIL
SKDDIIDVMKKLIDIRNGKGEVDDIDHLGNRRIRSVGEMAENQFRVGLVRVERAVKERLSLGDLDTLMPQ
DMINAKPISAAVKEFFGSSQLSQFMDQNNPLSEITHKRRISALGPGGLTRERAGFEVRDVHPTHYGRVCP
IETPEGPNIGLINSLSVYAQTNEYGFLETPYRKVTDGVVTDEIHYLSAIEEGNYVIAQANSNLDEEGHFV
EDLVTCRSKGESSLFSRDQVDYMDVSTQQVVSVGASLIPFLEHDDANRALMGANMQRQAVPTLRADKPLV
GTGMERAVAVDSGVTAVAKRGGVVQYVDASRIVIKVNEDEMYPGEAGIDIYNLTKYTRSNQNTCINQMPC
VSLGEPVERGDVLADGPSTDLGELALGQNMRVAFMPWNGYNFEDSILVSERVVQEDRFTTIHIQELACVS
RDTKLGPEEITADIPNVGEAALSKLDESGIVYIGAEVTGGDILVGKVTPKGETQLTPEEKLLRAIFGEKA
SDVKDSSLRVPNGVSGTVIDVQVFTRDGVEKDKRALEIEEMQLKQAKKDLSEELQILEAGLFSRIRAVLV
AGGVEAEKLDKLPRDRWLELGLTDEEKQNQLEQLAEQYDELKHEFEKKLEAKRRKITQGDDLAPGVLKIV
KVYLAVKRRIQPGDKMAGRHGNKGVISKINPIEDMPYDENGTPVDIVLNPLGVPSRMNIGQILETHLGMA
AKGIGDKINAMLKQQQEVAKLREFIQRAYDLGADVRQKVDLSTFSDEEVMRLAENLRKGMPIATPVFDGA
KEAEIKELLKLGDLPTSGQIRLYDGRTGEQFERPVTVGYMYMLKLNHLVDDKMHARSTGSYSLVTQQPLG
GKAQFGGQRFGEMEVWALEAYGAAYTLQEMLTVKSDDVNGRTKMYKNIVDGNHQMEPGMPESFNVLLKEI
RSLGINIELEDE
>RpoZ
MARVTVQDAVEKIGNRFDLVLVAARRARQMQVGGKDPLVPEENDKTTVIA
LREIEEGLINNQILDVRERQEQQEQEAAELQAVTAIAEGRR

**Comment by vladtheimpalerSr** [comment] 2018-01-17 16:52
![plink2](https://user-images.githubusercontent.com/35505821/35055283-d40115f4-fb7c-11e7-8a73-4083d13363d2.PNG)

**Comment by 01joy** [comment] 2018-01-18 01:31
@vladtheimpalerSr From your screenshot, reversed database had been generated successfully, so fasta file is ok. From your screenshot, maybe it has something to do with the mgf file. So could you provide me with the mgf file so that I can reproduce your issue.

**Comment by 01joy** [comment] 2018-01-18 01:52
Hi all,

As there are so many softwares to convert RAW to mgf, each one may give different mgf format. We strongly recommend you to load RAW files directly in pLink2 instead of converting RAW to mgf by other tools and load mgf.

When provided with RAW files, pParse will be called automatically to extract and calibrate multiple precursor ions for each tandem mass spectrum.

Thank you for using pLink2.

![image](https://user-images.githubusercontent.com/8603895/35076651-7b06ea42-fc34-11e7-8cb0-56c2b29d9d44.png)

**Comment by vladtheimpalerSr** [comment] 2018-01-18 02:38
I assume there different softwares that do that, but I convert mine using Proteome Discoverer. Providing no compatibility to either i) previous version of your software, or ii) the major proteomics soft virtually every mass spec comes with nowadays, doesn't seem like a very solid strategy for a piece of software that meant to be portable. No, really, I love it - PD generates "wrong" formats for pLink2, which work fine with pLink. Here is the link
https://www.dropbox.com/s/z6gzocnha59fige/DSM6A3.mgf?dl=0

**Comment by 01joy** [comment] 2018-01-18 04:02
Dear vladtheimpalerSr,

I finally found the problem, there are 4 whitespaces in your `RpoA` protein sequence in the fasta file. Once deleted, everything works fine. Did @armadillocommander meet the same problem?

We will fix this stupid bug in the next version by skipping all the non-alphabet characters in the fasta file to make pLink2 a more robust software.

I will send you the result searched by me through email.

By searching your data, I also want to confirm that pLink2 is compatible with mgf extracted by PD. But I still suggest that you load RAW files directly in pLink2. When provided with RAW files, pParse will be called automatically to extract and calibrate multiple precursor ions for each tandem mass spectrum.

Thank you for using pLink2.

**Comment by vladtheimpalerSr** [comment] 2018-01-18 17:44
I ran the fasta files through EMBOSS-Seqret, and pLink2 searched same mgf files with thus reformatted fasta files just fine. Thanks for the tip. I do think that a simple fix you suggested - filtering out non-alphanumerical stuff in future releases of pLink2 - is a good idea.

**Comment by armadillocommander** [comment] 2018-01-18 19:56
Hi @01joy ,

I did some experiment to confirm this issue. I created two .fasta file: fasta1.fasta is reformatted with script, and fasta2.fasta is in original format, which has a * at the end of each sequence.

[fasta_files.zip](https://github.com/pFindStudio/pLink2/files/1644242/fasta_files.zip)

The raw file was directly loaded and parsed with pParse2.0 in pLink2 automatically. During the search, the decoy fasta files with reversed sequences were generated successfully, however for fasta2_comb_rever.fasta, there's a * at the very beginning of each sequences. The search was completed with fasta1.fasta, and stopped at spectra loading step if fasta2.fasta was used. The last few of the output information in tmp/log.out is:

[pLink] Total spectra: 45153
[pLink] Loaded 3763 spectra, 3763 / 45153
[debug] Spectra preprocessing...
[debug] Creating peptide index...
[debug] Peptide Bit Index Initialized.
[pLink] Loaded 3763 spectra, 7526 / 45153
[debug] Spectra preprocessing...

So it's likely that the issue is caused by the non-standard AA code in sequence in fasta file.

**Comment by 01joy** [comment] 2018-01-19 02:02
Hi @armadillocommander ,

Thank you for your detailed experiment. The issue was indeed caused by the non-alphabet characters in sequence in fasta file.

When reversing fasta file, pLink2 just simply reverse the sequence without any validity check, only when parsing sequences in peptide index construction, it comes to the error. As a result, when checking the log file, it seems that it has something to do with the MGF file.

Anyway, I have fixed this bug by skipping all the non-alphabet characters when reversing fasta file. New version will be released at the end of this month.

**Comment by 01joy** [comment] 2018-01-31 15:40
Hi all,

This bug has been solved in pLink 2.3.0, which is released on January 31, 2018, please goto http://pfind.ict.ac.cn/software/pLink/index.html#Downloads to download the new version and try again.

Thanks for your feedback.

**Closed** 2018-02-02 03:48 UTC
Labels: bug
